/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edd_proyecto2;

import java.io.FileReader;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

/**
 *
 * @author joshu
 */
public class CargaMasivaUsuarios extends javax.swing.JFrame {

    //***filtro de archivo json
    private FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos JSON", "json");

    //ESTRUCTURA
    TablaDispersion.Lista tablaDispersion;

    /**
     * Creates new form CargaMasivaUsuarios
     */
    public CargaMasivaUsuarios(TablaDispersion.Lista tablaDispersion) {
        this.tablaDispersion = tablaDispersion;//recibo la estructura
        initComponents();
        setTitle("CARGA DE ARCHIVO JSON");//titulo de la ventana
        setLocationRelativeTo(null);//posicion en el centro
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbCargaMasiva = new javax.swing.JLabel();
        btnCargaArchivo = new javax.swing.JButton();
        txtRutaArchivo = new javax.swing.JTextField();
        lbNombreArchivo = new javax.swing.JLabel();
        txtNombreArchivo = new javax.swing.JTextField();
        btnRegistrarDatos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(5, 69, 107));

        jPanel1.setBackground(new java.awt.Color(7, 89, 137));

        lbCargaMasiva.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lbCargaMasiva.setForeground(new java.awt.Color(255, 255, 255));
        lbCargaMasiva.setText("realizar carga Masiva ");

        btnCargaArchivo.setText("Cargar Archivo");
        btnCargaArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargaArchivoActionPerformed(evt);
            }
        });

        lbNombreArchivo.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lbNombreArchivo.setForeground(new java.awt.Color(255, 255, 255));
        lbNombreArchivo.setText("Nombre Archivo");

        btnRegistrarDatos.setText("Registar Datos");
        btnRegistrarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarDatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbCargaMasiva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbNombreArchivo)
                            .addComponent(btnCargaArchivo))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegistrarDatos)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNombreArchivo)
                                .addGap(2, 2, 2))
                            .addComponent(txtRutaArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbCargaMasiva)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCargaArchivo)
                    .addComponent(txtRutaArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreArchivo)
                    .addComponent(txtNombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRegistrarDatos)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //EVENTO PARA CARGAR ARCHIVO JSON
    private void btnCargaArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargaArchivoActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        JFileChooser buscadorArchivos = new JFileChooser();
        //***** agregando filtro de archivos json al buscador
        buscadorArchivos.setFileFilter(filtro);//archivo json

        String nombreArchivo = "", rutaArchivo = "";

        int opcion = buscadorArchivos.showOpenDialog(this);
        if (opcion == JFileChooser.APPROVE_OPTION) {
            //mostrar el nombre del archivo selecionado
            nombreArchivo = buscadorArchivos.getSelectedFile().getName();
            //ruta del archivo
            rutaArchivo = buscadorArchivos.getSelectedFile().toString();
        }

        //********los muestro en los txt
        txtRutaArchivo.setText(rutaArchivo);
        txtNombreArchivo.setText(nombreArchivo);
    }//GEN-LAST:event_btnCargaArchivoActionPerformed

    //EVENTO PARA REGISTAR TODO
    private void btnRegistrarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarDatosActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        JSONParser parser = new JSONParser();
        try {
            //*********lectura del archivo json
            Object obj = parser.parse(new FileReader(txtRutaArchivo.getText()));
            JSONObject jsonObject = (JSONObject) obj;
            JSONArray lista = (JSONArray) jsonObject.get("CREAR_USUARIO");//para buscar categorias
            //**CICLO PARA RECORRE TODO EL ARRAY
            for (int i = 0; i < lista.size(); i++) {
                JSONObject usuarioNuevo = (JSONObject) lista.get(i);
                int carnet = Integer.parseInt("" + usuarioNuevo.get("Carnet"));//obtengo el valor
                String nombre = "" + usuarioNuevo.get("Nombre");
                String apellido = "" + usuarioNuevo.get("Apellido");
                String carrera = "" + usuarioNuevo.get("Carrera");
                String password = "" + usuarioNuevo.get("Password");
                //envio de datos a la estructura
                tablaDispersion.insertar(carnet, nombre, apellido, carrera, password);
            }
            
            //FIN DEL REGISTOR DEL ARCHIV JSON
            //CIERRE DE LA VENTAN
            dispose();
            tablaDispersion.reporteHash();//actualizacion del grafo

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Nose puedo cargar el archivo \n" + e);
        }
    }//GEN-LAST:event_btnRegistrarDatosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargaArchivo;
    private javax.swing.JButton btnRegistrarDatos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbCargaMasiva;
    private javax.swing.JLabel lbNombreArchivo;
    private javax.swing.JTextField txtNombreArchivo;
    private javax.swing.JTextField txtRutaArchivo;
    // End of variables declaration//GEN-END:variables
}
